version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.3.0
    steps:
      - checkout
      - run: npm install
      - run: npm run verify
  package:
    machine:
      enabled: true
    steps:
      - checkout
      - run: npm install
      - run: npm run build:all
      - run:
          command: |
            cd dist-firefox
            npx web-ext build
            npx web-ext sign --api-key $AMO_JWT_ISSUER --api-secret $AMO_JWT_SECRET
      - persist_to_workspace:
          root: dist-firefox/web-ext-artifacts
          paths:
            - *
  deploy:
    docker:
      - image: circleci/go:1.9.2
      - steps:
          - attach_workspace:
              at: dist-firefox/web-ext-artifacts
          - run: ls -al dist-firefox/web-ext-artifacts
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - package:
          requires:
            - build
      - deploy:
          requires:
            - package
